// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkD23IdNg3h5XsikrHuPweDY1pzz6PQmE',
    appId: '1:295235651509:web:ac6fc3bc7a595c5c72bbfc',
    messagingSenderId: '295235651509',
    projectId: 'estudiar-543ab',
    authDomain: 'estudiar-543ab.firebaseapp.com',
    storageBucket: 'estudiar-543ab.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR5HiAqZMNAUJGVcGKOXzyo5vXPjyRaU0',
    appId: '1:295235651509:android:5b489376afcd0e5372bbfc',
    messagingSenderId: '295235651509',
    projectId: 'estudiar-543ab',
    storageBucket: 'estudiar-543ab.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWVQA1NP8FVd-OJ4_bS2wmpwnPS0adAvk',
    appId: '1:295235651509:ios:272b63f27a36ccf472bbfc',
    messagingSenderId: '295235651509',
    projectId: 'estudiar-543ab',
    storageBucket: 'estudiar-543ab.firebasestorage.app',
    iosClientId: '295235651509-0ig2688001kis605ud2bsjcn09t7pijc.apps.googleusercontent.com',
    iosBundleId: 'com.estudiar.estudiar',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWVQA1NP8FVd-OJ4_bS2wmpwnPS0adAvk',
    appId: '1:295235651509:ios:272b63f27a36ccf472bbfc',
    messagingSenderId: '295235651509',
    projectId: 'estudiar-543ab',
    storageBucket: 'estudiar-543ab.firebasestorage.app',
    iosClientId: '295235651509-0ig2688001kis605ud2bsjcn09t7pijc.apps.googleusercontent.com',
    iosBundleId: 'com.estudiar.estudiar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkD23IdNg3h5XsikrHuPweDY1pzz6PQmE',
    appId: '1:295235651509:web:42b6c40e010796fc72bbfc',
    messagingSenderId: '295235651509',
    projectId: 'estudiar-543ab',
    authDomain: 'estudiar-543ab.firebaseapp.com',
    storageBucket: 'estudiar-543ab.firebasestorage.app',
  );
}
